Repository bianjieai/tibc-go, pull requests merged in 2021-09, with the labels that each got.

#25 Implement tics-008
  go.mod
  go.sum
  modules/tibc/core/02-client/keeper/keeper_test.go
  modules/tibc/core/02-client/proposal_handler_test.go
  modules/tibc/core/02-client/simulation/decoder_test.go
  modules/tibc/core/02-client/types/genesis_test.go
  modules/tibc/core/02-client/types/query.pb.gw.go
  modules/tibc/core/04-packet/keeper/grpc_query_test.go
  modules/tibc/core/04-packet/keeper/keeper_test.go
  modules/tibc/core/04-packet/keeper/packet_test.go
  modules/tibc/core/26-routing/keeper/grpc_query_test.go
  modules/tibc/core/26-routing/proposal_handler_test.go
  modules/tibc/core/genesis_test.go
  modules/tibc/core/simulation/decoder_test.go
  modules/tibc/core/types/codec.go
  modules/tibc/light-clients/07-tendermint/types/client_state_test.go
  modules/tibc/light-clients/07-tendermint/types/genesis_test.go
  modules/tibc/light-clients/07-tendermint/types/store_test.go
  modules/tibc/light-clients/07-tendermint/types/update_test.go
  modules/tibc/light-clients/08-bsc/module.go
  modules/tibc/light-clients/08-bsc/types/bsc.go
  modules/tibc/light-clients/08-bsc/types/bsc.pb.go
  modules/tibc/light-clients/08-bsc/types/bsc_test.go
  modules/tibc/light-clients/08-bsc/types/client_state.go
  modules/tibc/light-clients/08-bsc/types/codec.go
  modules/tibc/light-clients/08-bsc/types/consensus_state.go
  modules/tibc/light-clients/08-bsc/types/errors.go
  modules/tibc/light-clients/08-bsc/types/hashing.go
  modules/tibc/light-clients/08-bsc/types/header.go
  modules/tibc/light-clients/08-bsc/types/snapshot.go
  modules/tibc/light-clients/08-bsc/types/store.go
  modules/tibc/light-clients/08-bsc/types/types.go
  modules/tibc/light-clients/08-bsc/types/update.go
  modules/tibc/light-clients/08-bsc/types/update_test.go
  modules/tibc/testing/chain.go
  modules/tibc/testing/endpoint.go
  modules/tibc/testing/path.go
  proto/tibc/lightclients/bsc/v1/bsc.proto
  simapp/app.go
Labels: automerge

#35 Add rule validate to packet module
  modules/tibc/core/04-packet/keeper/packet.go
  modules/tibc/core/26-routing/keeper/keeper.go
Labels: automerge

#33 Update 08-bsc ExportMetadata
  modules/tibc/light-clients/07-tendermint/types/genesis.go
  modules/tibc/light-clients/08-bsc/types/client_state.go
  modules/tibc/light-clients/08-bsc/types/genesis_test.go
  modules/tibc/light-clients/08-bsc/types/store.go
Labels: automerge

#36 Fix transferowner bug when updateRestricted is true
  modules/tibc/apps/nft_transfer/keeper/relay.go
Labels: bug, automerge

#39 Delete channel sequence
  modules/tibc/core/04-packet/types/genesis.go
  modules/tibc/core/04-packet/types/genesis.pb.go
  proto/tibc/core/packet/v1/genesis.proto
Labels: automerge

#41 fix packet bugs
  modules/tibc/core/04-packet/client/cli/cli.go
  modules/tibc/core/04-packet/client/cli/flags.go
  modules/tibc/core/04-packet/client/cli/tx.go
  modules/tibc/core/04-packet/keeper/grpc_query_test.go
  modules/tibc/core/04-packet/keeper/keeper_test.go
  modules/tibc/core/04-packet/keeper/packet.go
  modules/tibc/core/04-packet/keeper/packet_test.go
  modules/tibc/core/04-packet/module.go
  modules/tibc/core/26-routing/client/cli/cli.go
  modules/tibc/core/26-routing/module.go
  modules/tibc/core/client/cli/cli.go
  modules/tibc/core/genesis.go
  modules/tibc/core/keeper/grpc_query.go
  modules/tibc/core/keeper/keeper.go
  modules/tibc/core/keeper/msg_server.go
  modules/tibc/light-clients/07-tendermint/types/genesis.go
  modules/tibc/light-clients/08-bsc/types/store.go
  modules/tibc/testing/chain.go
  modules/tibc/testing/endpoint.go
  modules/tibc/testing/path.go
  simapp/app.go
Labels: automerge

#37 Add tx flag to client-update
  modules/tibc/core/02-client/client/cli/tx.go
Labels: automerge

#43 26 routing genesis
  modules/tibc/core/04-packet/types/genesis.go
  modules/tibc/core/04-packet/types/genesis_test.go
  modules/tibc/core/26-routing/genesis.go
  modules/tibc/core/26-routing/keeper/grpc_query.go
  modules/tibc/core/26-routing/keeper/keeper.go
  modules/tibc/core/26-routing/types/errors.go
  modules/tibc/core/26-routing/types/genesis.go
  modules/tibc/core/types/genesis.go
Labels: automerge

#42 Modify JSON encoding to protobuf
  modules/tibc/apps/nft_transfer/moudle.go
  modules/tibc/apps/nft_transfer/types/packet.go
Labels: automerge

#38 Optimize cross-chain generation denom rules
  modules/tibc/apps/nft_transfer/keeper/relay.go
  modules/tibc/apps/nft_transfer/keeper/relay_test.go
Labels: automerge

#45 fix routing cmd
  modules/tibc/apps/nft_transfer/types/packet.go
  modules/tibc/core/02-client/client/cli/cli.go
  modules/tibc/core/26-routing/client/cli/cli.go
  modules/tibc/core/26-routing/client/cli/tx.go
  modules/tibc/core/26-routing/module.go
  modules/tibc/core/26-routing/types/codec.go
  modules/tibc/core/26-routing/types/routing.pb.go
  modules/tibc/core/client/cli/cli.go
  modules/tibc/core/module.go
  modules/tibc/core/types/codec.go
  modules/tibc/light-clients/09-eth/types/client_state.go
  modules/tibc/light-clients/09-eth/types/codec.go
  modules/tibc/light-clients/09-eth/types/errors.go
  modules/tibc/light-clients/09-eth/types/eth.go
  modules/tibc/light-clients/09-eth/types/header.go
  modules/tibc/light-clients/09-eth/types/store.go
  modules/tibc/light-clients/09-eth/types/update.go
  proto/tibc/core/routing/v1/routing.proto
  simapp/app.go
Labels: automerge

#44 fix CommitPacket's arg
  modules/tibc/core/04-packet/keeper/packet.go
  modules/tibc/core/04-packet/types/packet.go
  modules/tibc/core/04-packet/types/packet_test.go
  modules/tibc/core/26-routing/proposal_handler_test.go
  modules/tibc/light-clients/07-tendermint/types/client_state_test.go
  modules/tibc/testing/path.go
Labels: automerge

#46 Add routing genesis test
  modules/tibc/core/26-routing/types/genesis_test.go
  modules/tibc/core/26-routing/types/regex.go
Labels: automerge

#48 Add eth light client update test
  modules/tibc/core/exported/client.go
  modules/tibc/light-clients/09-eth/types/client_state.go
  modules/tibc/light-clients/09-eth/types/codec.go
  modules/tibc/light-clients/09-eth/types/errors.go
  modules/tibc/light-clients/09-eth/types/eth.go
  modules/tibc/light-clients/09-eth/types/eth_test.go
  modules/tibc/light-clients/09-eth/types/header.go
  modules/tibc/light-clients/09-eth/types/sealer.go
  modules/tibc/light-clients/09-eth/types/store.go
  modules/tibc/light-clients/09-eth/types/update.go
  modules/tibc/light-clients/09-eth/types/update_test.go
  modules/tibc/light-clients/09-eth/types/verify_header.go
Labels: automerge

#51 Unify form of verify
  modules/tibc/core/04-packet/keeper/packet.go
  modules/tibc/core/exported/client.go
  modules/tibc/light-clients/07-tendermint/types/client_state.go
  modules/tibc/light-clients/07-tendermint/types/client_state_test.go
  modules/tibc/light-clients/08-bsc/types/client_state.go
  modules/tibc/light-clients/09-eth/types/client_state.go
Labels: automerge

#50 Fix internal bug
  modules/tibc/apps/nft_transfer/types/errors.go
Labels: bug, automerge

#52 Fix packet cmd bug
  modules/tibc/core/04-packet/client/cli/tx.go
Labels: automerge

#49 WIP: Fix 02-client query error
  modules/tibc/core/02-client/client/cli/query.go
  modules/tibc/core/02-client/client/utils/utils.go
Labels: bug, automerge

#55 Change the ack encoding to protobuf
  modules/tibc/apps/nft_transfer/moudle.go
  modules/tibc/core/04-packet/types/packet.go
Labels: automerge

#56 Implement relayers query & consensus_state query
  modules/tibc/core/02-client/client/utils/utils.go
  modules/tibc/core/keeper/grpc_query.go
Labels: automerge

#65 Fix relay chain can't return error ack problem
  modules/tibc/core/04-packet/keeper/packet.go
Labels: automerge

#72 Fix consensus states query
  modules/tibc/core/02-client/keeper/grpc_query.go
Labels: bug

#63 Finish denomtrace && re-modify the nft class specification function
  go.sum
  modules/tibc/apps/nft_transfer/client/cli/cli.go
  modules/tibc/apps/nft_transfer/client/cli/query.go
  modules/tibc/apps/nft_transfer/keeper/encoding.go
  modules/tibc/apps/nft_transfer/keeper/grpc_query.go
  modules/tibc/apps/nft_transfer/keeper/keeper.go
  modules/tibc/apps/nft_transfer/keeper/relay.go
  modules/tibc/apps/nft_transfer/keeper/relay_test.go
  modules/tibc/apps/nft_transfer/moudle.go
  modules/tibc/apps/nft_transfer/transfer_test.go
  modules/tibc/apps/nft_transfer/types/errors.go
  modules/tibc/apps/nft_transfer/types/events.go
  modules/tibc/apps/nft_transfer/types/keys.go
  modules/tibc/apps/nft_transfer/types/nft.go
  modules/tibc/apps/nft_transfer/types/nft_transfer.pb.go
  modules/tibc/apps/nft_transfer/types/packet.go
  modules/tibc/apps/nft_transfer/types/query.pb.go
  modules/tibc/apps/nft_transfer/types/query.pb.gw.go
  modules/tibc/apps/nft_transfer/types/trace.go
  proto/tibc/apps/nft_transfer/v1/nft_transfer.proto
  proto/tibc/apps/nft_transfer/v1/query.proto
  simapp/app.go
Labels: automerge

#73 Fix sorting bug and update eth client
  modules/tibc/core/02-client/client/cli/query.go
  modules/tibc/core/02-client/keeper/grpc_query.go
  modules/tibc/core/02-client/keeper/keeper.go
  modules/tibc/core/24-host/keys.go
  modules/tibc/light-clients/07-tendermint/types/store.go
  modules/tibc/light-clients/09-eth/types/client_state.go
  modules/tibc/light-clients/09-eth/types/eth.go
  modules/tibc/light-clients/09-eth/types/eth.pb.go
  modules/tibc/light-clients/09-eth/types/eth_test.go
  modules/tibc/light-clients/09-eth/types/genesis_test.go
  modules/tibc/light-clients/09-eth/types/header.go
  modules/tibc/light-clients/09-eth/types/store.go
  modules/tibc/light-clients/09-eth/types/update.go
  modules/tibc/light-clients/09-eth/types/update_test.go
  modules/tibc/light-clients/09-eth/types/verify_header.go
  proto/tibc/lightclients/eth/v1/eth.proto
  simapp/app.go
Labels: automerge

#80 Update class prefix as tibcnft & make format
  modules/tibc/apps/nft_transfer/keeper/relay.go
  modules/tibc/apps/nft_transfer/keeper/relay_test.go
  modules/tibc/apps/nft_transfer/transfer_test.go
  modules/tibc/core/02-client/keeper/proposal_test.go
  modules/tibc/testing/mock/mock.go
Labels: automerge
