Repository bianjieai/tibc-go, pull requests merged in 2021-08, with the labels that each got.

#3 Refactor port to routing
  modules/tibc/core/04-packet/keeper/keeper.go
  modules/tibc/core/04-packet/types/expected_keepers.go
  modules/tibc/core/05-port/keeper/keeper.go
  modules/tibc/core/05-port/keeper/keeper_test.go
  modules/tibc/core/05-port/types/errors.go
  modules/tibc/core/24-host/keys.go
  modules/tibc/core/26-routing/keeper/keeper.go
  modules/tibc/core/26-routing/keeper/keeper_test.go
  modules/tibc/core/26-routing/types/errors.go
  modules/tibc/core/26-routing/types/keys.go
  modules/tibc/core/26-routing/types/module.go
  modules/tibc/core/26-routing/types/router.go
  modules/tibc/core/26-routing/types/utils.go
  modules/tibc/core/keeper/keeper.go
  modules/tibc/core/keeper/msg_server.go
  modules/tibc/core/spec/01_concepts.md
  modules/tibc/core/spec/02_state.md
  modules/tibc/core/spec/03_state_transitions.md
  modules/tibc/core/spec/04_messages.md
  modules/tibc/core/spec/05_callbacks.md
  modules/tibc/core/spec/06_events.md
  modules/tibc/core/spec/07_params.md
  modules/tibc/core/spec/README.md
  modules/tibc/spec/README.md
  simapp/app.go
Labels: tics-026

#4 Remove capability keeper
  modules/tibc/core/04-packet/keeper/keeper.go
  modules/tibc/core/04-packet/keeper/packet.go
  modules/tibc/core/keeper/keeper.go
  modules/tibc/core/keeper/msg_server.go
Labels: tics-004

#5 Fix mock chain
  modules/tibc/core/02-client/client/proposal_handler.go
  modules/tibc/core/02-client/keeper/keeper_test.go
  modules/tibc/core/02-client/keeper/relayer.go
  modules/tibc/core/02-client/simulation/decoder_test.go
  modules/tibc/core/02-client/types/errors.go
  modules/tibc/core/04-packet/simulation/decoder_test.go
  modules/tibc/core/04-packet/types/errors.go
  modules/tibc/core/04-packet/types/msgs_test.go
  modules/tibc/core/23-commitment/types/errors.go
  modules/tibc/core/26-routing/keeper/keeper_test.go
  modules/tibc/core/26-routing/types/errors.go
  modules/tibc/core/simulation/decoder_test.go
  modules/tibc/light-clients/07-tendermint/types/errors.go
  modules/tibc/light-clients/07-tendermint/types/tendermint_test.go
  modules/tibc/testing/chain.go
  modules/tibc/testing/coordinator.go
  modules/tibc/testing/types.go
Labels: test

#6 Improve 02-client code
  modules/tibc/core/02-client/abci.go
  modules/tibc/core/02-client/client/cli/tx.go
  modules/tibc/core/02-client/client/proposal_handler.go
  modules/tibc/core/02-client/genesis.go
  modules/tibc/core/02-client/proposal_handler.go
  modules/tibc/core/02-client/types/client.go
  modules/tibc/core/02-client/types/genesis.go
  modules/tibc/core/02-client/types/genesis_test.go
  modules/tibc/core/02-client/types/keys.go
  modules/tibc/core/02-client/types/keys_test.go
  modules/tibc/core/02-client/types/proposal.go
  simapp/app.go
Labels: tics-002

#7 Implement tendermint light client
  modules/tibc/core/02-client/client/cli/cli.go
  modules/tibc/core/02-client/client/cli/tx.go
  modules/tibc/core/02-client/module.go
  modules/tibc/core/02-client/proposal_handler.go
  modules/tibc/core/04-packet/keeper/packet.go
  modules/tibc/core/client/cli/cli.go
  modules/tibc/core/exported/client.go
  modules/tibc/light-clients/07-tendermint/client/cli/cli.go
  modules/tibc/light-clients/07-tendermint/client/cli/tx.go
  modules/tibc/light-clients/07-tendermint/module.go
  modules/tibc/light-clients/07-tendermint/types/client_state.go
  modules/tibc/light-clients/07-tendermint/types/client_state_test.go
  modules/tibc/light-clients/07-tendermint/types/genesis_test.go
  modules/tibc/light-clients/07-tendermint/types/store.go
  modules/tibc/light-clients/07-tendermint/types/store_test.go
  modules/tibc/light-clients/07-tendermint/types/tendermint.pb.go
  modules/tibc/light-clients/07-tendermint/types/update.go
  modules/tibc/light-clients/07-tendermint/types/update_test.go
  modules/tibc/light-clients/07-tendermint/types/upgrade.go
  modules/tibc/light-clients/07-tendermint/types/upgrade_test.go
  modules/tibc/testing/chain.go
  proto/tibc/lightclients/tendermint/v1/tendermint.proto
  simapp/sim_test.go
Labels: tics-007

#11 Fix tendermint client test
  modules/tibc/core/02-client/keeper/client_test.go
  modules/tibc/core/02-client/keeper/grpc_query_test.go
  modules/tibc/core/02-client/keeper/keeper_test.go
  modules/tibc/core/02-client/proposal_handler.go
  modules/tibc/core/02-client/simulation/decoder_test.go
  modules/tibc/core/02-client/types/codec_test.go
  modules/tibc/core/02-client/types/genesis.go
  modules/tibc/core/02-client/types/genesis_test.go
  modules/tibc/core/genesis_test.go
  modules/tibc/core/keeper/msg_server_test.go
  modules/tibc/core/module.go
  modules/tibc/light-clients/07-tendermint/types/client_state.go
  modules/tibc/light-clients/07-tendermint/types/client_state_test.go
  modules/tibc/light-clients/07-tendermint/types/store.go
  modules/tibc/light-clients/07-tendermint/types/store_test.go
  modules/tibc/light-clients/07-tendermint/types/tendermint_test.go
  modules/tibc/light-clients/07-tendermint/types/update_test.go
  modules/tibc/testing/chain.go
  modules/tibc/testing/config.go
  modules/tibc/testing/coordinator.go
  modules/tibc/testing/endpoint.go
  modules/tibc/testing/path.go
  simapp/test_helpers.go
Labels: tics-007

#14 Fix some bug
  modules/tibc/core/02-client/client/utils/utils.go
  modules/tibc/core/02-client/types/codec.go
  modules/tibc/core/02-client/types/proposal.go
  modules/tibc/testing/chain.go
  simapp/app.go
Labels: tics-002

#12 Add routing packet
  go.mod
  go.sum
  modules/tibc/core/02-client/proposal_handler_test.go
  modules/tibc/core/02-client/types/genesis.go
  modules/tibc/core/04-packet/keeper/keeper.go
  modules/tibc/core/04-packet/keeper/packet.go
  modules/tibc/core/04-packet/types/expected_keepers.go
  modules/tibc/core/04-packet/types/msgs.go
  modules/tibc/core/04-packet/types/packet.go
  modules/tibc/core/04-packet/types/packet.pb.go
  modules/tibc/core/04-packet/types/tx.pb.go
  modules/tibc/core/24-host/keys.go
  modules/tibc/core/24-host/parse.go
  modules/tibc/core/26-routing/keeper/keeper.go
  modules/tibc/core/26-routing/types/errors.go
  modules/tibc/core/26-routing/types/regex.go
  modules/tibc/core/keeper/keeper.go
  modules/tibc/core/keeper/msg_server.go
  modules/tibc/testing/endpoint.go
  proto/tibc/core/packet/v1/packet.proto
  proto/tibc/core/packet/v1/tx.proto
Labels: tics-004

#19 Fix all test
  .github/workflows/TestUnit.yml
  .github/workflows/automerge.yml
  go.mod
  go.sum
  modules/tibc/apps/nft_transfer/keeper/relay_test.go
  modules/tibc/apps/nft_transfer/moudle.go
  modules/tibc/apps/nft_transfer/transfer_test.go
  modules/tibc/core/02-client/types/client_test.go
  modules/tibc/core/04-packet/keeper/grpc_query_test.go
  modules/tibc/core/04-packet/keeper/keeper_test.go
  modules/tibc/core/04-packet/keeper/packet.go
  modules/tibc/core/04-packet/keeper/packet_test.go
  modules/tibc/core/04-packet/simulation/decoder_test.go
  modules/tibc/core/04-packet/types/genesis_test.go
  modules/tibc/core/04-packet/types/msgs_test.go
  modules/tibc/core/04-packet/types/packet_test.go
  modules/tibc/core/26-routing/keeper/keeper.go
  modules/tibc/core/26-routing/keeper/keeper_test.go
  modules/tibc/core/genesis_test.go
  modules/tibc/core/simulation/decoder_test.go
  modules/tibc/core/simulation/genesis_test.go
  modules/tibc/light-clients/07-tendermint/types/client_state_test.go
  modules/tibc/light-clients/07-tendermint/types/update_test.go
  modules/tibc/testing/endpoint.go
  modules/tibc/testing/mock/mock.go
  simapp/app.go
Labels: automerge

#20 Rename clientId to chainName
  modules/tibc/core/02-client/client/cli/query.go
  modules/tibc/core/02-client/client/utils/utils.go
  modules/tibc/core/02-client/keeper/client.go
  modules/tibc/core/02-client/keeper/grpc_query.go
  modules/tibc/core/02-client/keeper/grpc_query_test.go
  modules/tibc/core/02-client/keeper/keeper.go
  modules/tibc/core/02-client/keeper/keeper_test.go
  modules/tibc/core/02-client/simulation/decoder_test.go
  modules/tibc/core/02-client/types/genesis.go
  modules/tibc/core/02-client/types/genesis_test.go
  modules/tibc/core/02-client/types/msgs_test.go
  modules/tibc/core/02-client/types/proposal_test.go
  modules/tibc/core/04-packet/keeper/packet.go
  modules/tibc/core/04-packet/types/expected_keepers.go
  modules/tibc/core/exported/client.go
  modules/tibc/core/exported/connection.go
  modules/tibc/core/keeper/msg_server_test.go
  modules/tibc/core/simulation/decoder_test.go
  modules/tibc/light-clients/07-tendermint/types/tendermint_test.go
  modules/tibc/light-clients/07-tendermint/types/update_test.go
  modules/tibc/testing/chain.go
  modules/tibc/testing/endpoint.go
  proto/tibc/core/client/v1/genesis.proto
Labels: automerge

#16 Update packet function
  modules/tibc/core/04-packet/keeper/keeper.go
  modules/tibc/core/04-packet/keeper/packet.go
  modules/tibc/core/04-packet/types/errors.go
  modules/tibc/core/04-packet/types/events.go
  modules/tibc/core/24-host/keys.go
  modules/tibc/core/exported/client.go
  modules/tibc/core/keeper/msg_server.go
  modules/tibc/light-clients/07-tendermint/types/client_state.go
  modules/tibc/testing/endpoint.go
Labels: automerge

#21 Add unit test && resolve conflict
  modules/tibc/apps/nft_transfer/keeper/relay.go
  modules/tibc/apps/nft_transfer/keeper/relay_test.go
Labels: automerge

#22 Update packet query proto file
  modules/tibc/core/02-client/types/genesis.pb.go
  modules/tibc/core/04-packet/client/cli/cli.go
  modules/tibc/core/04-packet/client/cli/query.go
  modules/tibc/core/04-packet/client/utils/utils.go
  modules/tibc/core/04-packet/genesis.go
  modules/tibc/core/04-packet/keeper/grpc_query.go
  modules/tibc/core/04-packet/keeper/grpc_query_test.go
  modules/tibc/core/04-packet/keeper/keeper.go
  modules/tibc/core/04-packet/keeper/packet.go
  modules/tibc/core/04-packet/module.go
  modules/tibc/core/04-packet/simulation/decoder.go
  modules/tibc/core/04-packet/types/codec.go
  modules/tibc/core/04-packet/types/errors.go
  modules/tibc/core/04-packet/types/events.go
  modules/tibc/core/04-packet/types/expected_keepers.go
  modules/tibc/core/04-packet/types/genesis.go
  modules/tibc/core/04-packet/types/keys.go
  modules/tibc/core/04-packet/types/msgs.go
  modules/tibc/core/04-packet/types/query.pb.go
  modules/tibc/core/04-packet/types/query.pb.gw.go
  modules/tibc/core/04-packet/types/tx.pb.go
  modules/tibc/core/24-host/keys.go
  modules/tibc/core/24-host/validate.go
  modules/tibc/core/24-host/validate_test.go
  proto/tibc/core/packet/v1/query.proto
  proto/tibc/core/packet/v1/tx.proto
Labels: automerge

#24 Define bsc protobuf
  modules/tibc/core/02-client/types/query.pb.gw.go
  modules/tibc/core/04-packet/types/query.pb.gw.go
  modules/tibc/light-clients/08-bsc/types/bsc.pb.go
  proto/tibc/lightclients/bsc/v1/bsc.proto
Labels: automerge

#26 update packet and routing cmd
  modules/tibc/core/04-packet/client/cli/cli.go
  modules/tibc/core/04-packet/client/cli/query.go
  modules/tibc/core/04-packet/client/utils/utils.go
  modules/tibc/core/04-packet/keeper/grpc_query.go
  modules/tibc/core/04-packet/keeper/grpc_query_test.go
  modules/tibc/core/04-packet/keeper/keeper.go
  modules/tibc/core/04-packet/keeper/packet.go
  modules/tibc/core/04-packet/types/codec.go
  modules/tibc/core/04-packet/types/errors.go
  modules/tibc/core/04-packet/types/events.go
  modules/tibc/core/04-packet/types/keys.go
  modules/tibc/core/04-packet/types/keys_test.go
  modules/tibc/core/04-packet/types/msgs.go
  modules/tibc/core/04-packet/types/packet.go
  modules/tibc/core/04-packet/types/packet.pb.go
  modules/tibc/core/04-packet/types/query.go
  modules/tibc/core/04-packet/types/query.pb.go
  modules/tibc/core/04-packet/types/query.pb.gw.go
  modules/tibc/core/04-packet/types/tx.pb.go
  modules/tibc/core/24-host/keys.go
  modules/tibc/core/26-routing/client/cli/cli.go
  modules/tibc/core/26-routing/client/cli/query.go
  modules/tibc/core/26-routing/genesis.go
  modules/tibc/core/26-routing/keeper/grpc_query.go
  modules/tibc/core/26-routing/keeper/grpc_query_test.go
  modules/tibc/core/26-routing/keeper/keeper_test.go
  modules/tibc/core/26-routing/module.go
  modules/tibc/core/26-routing/types/errors.go
  modules/tibc/core/26-routing/types/genesis.pb.go
  modules/tibc/core/26-routing/types/query.pb.go
  modules/tibc/core/26-routing/types/query.pb.gw.go
  modules/tibc/core/26-routing/types/utils.go
  modules/tibc/core/client/cli/cli.go
  modules/tibc/core/exported/channel.go
  modules/tibc/core/exported/connection.go
  modules/tibc/core/exported/packet.go
  modules/tibc/core/keeper/grpc_query.go
  modules/tibc/core/keeper/msg_server.go
  modules/tibc/core/types/query.go
  modules/tibc/testing/endpoint.go
  proto/tibc/core/packet/v1/packet.proto
  proto/tibc/core/packet/v1/query.proto
  proto/tibc/core/packet/v1/tx.proto
  proto/tibc/core/routing/v1/genesis.proto
  proto/tibc/core/routing/v1/query.proto
Labels: automerge

#23 Add transfer_test and fix some bug
  modules/tibc/apps/nft_transfer/client/cli/tx.go
  modules/tibc/apps/nft_transfer/keeper/relay.go
  modules/tibc/apps/nft_transfer/keeper/relay_test.go
  modules/tibc/apps/nft_transfer/moudle.go
  modules/tibc/apps/nft_transfer/transfer_test.go
  modules/tibc/apps/nft_transfer/types/genesis.go
  modules/tibc/apps/nft_transfer/types/genesis.pb.go
  modules/tibc/apps/nft_transfer/types/keys.go
  modules/tibc/testing/endpoint.go
  proto/tibc/apps/nft_transfer/v1/genesis.proto
Labels: automerge

#27 add a proposal to set routing rules
  go.sum
  modules/tibc/core/24-host/errors.go
  modules/tibc/core/24-host/validate.go
  modules/tibc/core/24-host/validate_test.go
  modules/tibc/core/26-routing/client/cli/tx.go
  modules/tibc/core/26-routing/keeper/grpc_query.go
  modules/tibc/core/26-routing/keeper/grpc_query_test.go
  modules/tibc/core/26-routing/keeper/keeper_test.go
  modules/tibc/core/26-routing/keeper/proposal.go
  modules/tibc/core/26-routing/proposal_handler.go
  modules/tibc/core/26-routing/proposal_handler_test.go
  modules/tibc/core/26-routing/types/proposal.go
  modules/tibc/core/26-routing/types/proposal_test.go
  modules/tibc/core/26-routing/types/routing.pb.go
  proto/tibc/core/routing/v1/routing.proto
  simapp/app.go
Labels: automerge

#28 Update routing genesis
  modules/tibc/core/04-packet/keeper/packet.go
  modules/tibc/core/04-packet/keeper/packet_test.go
  modules/tibc/core/26-routing/genesis.go
  modules/tibc/core/genesis.go
  modules/tibc/core/types/genesis.pb.go
  proto/tibc/core/types/v1/genesis.proto
Labels: automerge

#29 Add clean packet msgs
  modules/tibc/core/handler.go
Labels: automerge

#30 Fix clean packet verify
  modules/tibc/core/04-packet/types/codec.go
  modules/tibc/light-clients/07-tendermint/types/client_state.go
Labels: automerge

#31 Upgrade tibc-go dependecy
  go.mod
  go.sum
Labels: automerge

#32 Fix bsc client and cleanup
  modules/tibc/core/02-client/keeper/keeper_test.go
  modules/tibc/core/02-client/proposal_handler_test.go
  modules/tibc/core/02-client/simulation/decoder_test.go
  modules/tibc/core/02-client/types/genesis_test.go
  modules/tibc/core/02-client/types/query.pb.gw.go
  modules/tibc/core/04-packet/keeper/grpc_query_test.go
  modules/tibc/core/04-packet/keeper/keeper_test.go
  modules/tibc/core/04-packet/keeper/packet_test.go
  modules/tibc/core/04-packet/types/query.pb.gw.go
  modules/tibc/core/26-routing/keeper/keeper_test.go
  modules/tibc/core/genesis_test.go
  modules/tibc/core/simulation/decoder_test.go
  modules/tibc/core/types/codec.go
  modules/tibc/light-clients/07-tendermint/types/client_state_test.go
  modules/tibc/light-clients/07-tendermint/types/genesis_test.go
  modules/tibc/light-clients/07-tendermint/types/store_test.go
  modules/tibc/light-clients/07-tendermint/types/update_test.go
  modules/tibc/light-clients/08-bsc/types/bsc.go
  modules/tibc/light-clients/08-bsc/types/bsc.pb.go
  modules/tibc/light-clients/08-bsc/types/bsc_test.go
  modules/tibc/light-clients/08-bsc/types/codec.go
  modules/tibc/light-clients/08-bsc/types/consensus_state.go
  modules/tibc/light-clients/08-bsc/types/header.go
  modules/tibc/light-clients/08-bsc/types/update.go
  modules/tibc/light-clients/08-bsc/types/update_test.go
  modules/tibc/testing/chain.go
  modules/tibc/testing/endpoint.go
  modules/tibc/testing/path.go
  proto/tibc/lightclients/bsc/v1/bsc.proto
  simapp/app.go
Labels: tics-002, automerge
